scrape_configs:
  - job_name: node_exporter
    scrape_interval: 5s
    static_configs:
    - targets: ['node_exporter_service:9100']
  
  - job_name: mariadb_exporter
    scrape_interval: 5s
    static_configs:
    - targets: ['mariadb_exporter_service:9104']