{
 "title": "OS General",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Network traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\"}[5m])",
     "legendFormat": "Traffic transmit"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[5m])",
     "legendFormat": "Traffic receive"
    }
   ]
  },
  {
   "title": "Free memory GiB",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/mapper/rootdir-main\",device_error=\"\",fstype=\"ext4\",mountpoint=\"/etc/hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File descriptor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"node_exporter_service:9100\", job=\"node_exporter\"}",
     "legendFormat": "File descriptor"
    }
   ]
  }
 ]
}